<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; padding: 28px; }
    h1 { font-size: 18px; font-weight: 800; color: #1e293b; margin-bottom: 2px; }
    .sub { font-size: 11px; color: #64748b; margin-bottom: 16px; }
    .meta { font-size: 10px; color: #64748b; margin-bottom: 14px; border-bottom: 1.5px solid #e2e8f0; padding-bottom: 10px; }
    .bal-banner { padding: 8px 14px; border-radius: 6px; font-size: 11px; font-weight: 600; margin-bottom: 16px; }
    .bal-ok  { background: #d1fae5; color: #065f46; }
    .bal-err { background: #fee2e2; color: #991b1b; }
    .section-title { font-size: 11px; font-weight: 800; padding: 7px 12px; }
    .assets-title      { background: #ede9fe; color: #4338ca; }
    .liabilities-title { background: #fee2e2; color: #dc2626; }
    .capital-title     { background: #fef3c7; color: #d97706; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
    thead th { background: #f8fafc; padding: 7px 12px; font-size: 10px; font-weight: 700; text-transform: uppercase; color: #64748b; text-align: left; border-bottom: 1.5px solid #e2e8f0; }
    thead th.num { text-align: right; }
    tbody td { padding: 6px 12px; font-size: 11px; border-bottom: 1px solid #f1f5f9; color: #374151; }
    tbody td.num { text-align: right; font-family: monospace; }
    tfoot td { padding: 8px 12px; font-weight: 700; background: #f8fafc; border-top: 2px solid #e2e8f0; }
    tfoot td.num { text-align: right; font-family: monospace; }
    .grand-total { background: #1e293b !important; color: #fff !important; }
    .footer { margin-top: 20px; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head>
<body>
    <h1>Balance Sheet</h1>
    <p class="sub">Statement of financial position — Assets = Liabilities + Capital</p>
    <div class="meta">
        As of: <strong>{{ $asOf }}</strong> &nbsp;&bull;&nbsp;
        Generated: @fdatetime(now())
    </div>

    @php
        $fmt      = fn($n) => '₹' . number_format(abs($n), 2);
        $balanced = round($totalAssets, 2) === round($totalLCE, 2);
    @endphp

    <div class="bal-banner {{ $balanced ? 'bal-ok' : 'bal-err' }}">
        @if($balanced)
            ✓ Balanced — Assets {{ $fmt($totalAssets) }} = Liabilities + Capital {{ $fmt($totalLCE) }}
        @else
            ✗ NOT Balanced — Difference: {{ $fmt(abs($totalAssets - $totalLCE)) }}
        @endif
    </div>

    <!-- Assets -->
    <div class="section-title assets-title">Assets</div>
    <table>
        <thead><tr><th>Account</th><th class="num">Amount</th></tr></thead>
        <tbody>
            @foreach($assets as $row)
            <tr>
                <td>{{ $row['ledger_name'] }}</td>
                <td class="num" style="color:#4338ca">{{ $fmt($row['amount']) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr><td style="text-align:right;font-weight:700;">Total Assets</td><td class="num" style="color:#4338ca">{{ $fmt($totalAssets) }}</td></tr>
        </tfoot>
    </table>

    <!-- Liabilities -->
    <div class="section-title liabilities-title">Liabilities</div>
    <table>
        <thead><tr><th>Account</th><th class="num">Amount</th></tr></thead>
        <tbody>
            @foreach($liabilities as $row)
            <tr>
                <td>{{ $row['ledger_name'] }}</td>
                <td class="num" style="color:#dc2626">{{ $fmt($row['amount']) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr><td style="text-align:right;font-weight:700;">Total Liabilities</td><td class="num" style="color:#dc2626">{{ $fmt($totalLiabilities) }}</td></tr>
        </tfoot>
    </table>

    <!-- Capital -->
    <div class="section-title capital-title">Capital &amp; Reserves</div>
    <table>
        <thead><tr><th>Account</th><th class="num">Amount</th></tr></thead>
        <tbody>
            @foreach($capital as $row)
            <tr>
                <td>{{ $row['ledger_name'] }}</td>
                <td class="num" style="color:#d97706">{{ $fmt($row['amount']) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr><td style="text-align:right;font-weight:700;">Total Capital</td><td class="num" style="color:#d97706">{{ $fmt($totalCapital) }}</td></tr>
            <tr class="grand-total"><td style="text-align:right;color:#fff;font-weight:800;">Total Liabilities + Capital</td><td class="num" style="color:#fff">{{ $fmt($totalLCE) }}</td></tr>
        </tfoot>
    </table>

    <div class="footer">Generated by School ERP &bull; {{ config('app.name') }}</div>
</body>
</html>
