<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; padding: 28px; }
    h1 { font-size: 17px; font-weight: 800; color: #1e293b; margin-bottom: 2px; }
    .sub { font-size: 11px; color: #64748b; margin-bottom: 16px; }
    .meta { font-size: 10px; color: #64748b; margin-bottom: 14px; border-bottom: 1.5px solid #e2e8f0; padding-bottom: 10px; }
    .summary { display: flex; gap: 20px; margin-bottom: 16px; }
    .sum-item { flex: 1; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px; }
    .sum-label { font-size: 9px; font-weight: 700; text-transform: uppercase; color: #94a3b8; }
    .sum-value { font-size: 13px; font-weight: 800; font-family: monospace; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; }
    thead th { background: #f8fafc; padding: 7px 10px; font-size: 10px; font-weight: 700; text-transform: uppercase; color: #64748b; text-align: left; border-bottom: 1.5px solid #e2e8f0; }
    thead th.num { text-align: right; }
    tbody td { padding: 6px 10px; font-size: 11px; border-bottom: 1px solid #f1f5f9; color: #374151; }
    tbody td.num { text-align: right; font-family: monospace; }
    tfoot td { padding: 8px 10px; font-weight: 700; background: #f8fafc; border-top: 2px solid #e2e8f0; }
    tfoot td.num { text-align: right; font-family: monospace; }
    .footer { margin-top: 20px; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head>
<body>
    <h1>Ledger Book — {{ $ledger['name'] }}</h1>
    <p class="sub">{{ $ledger['ledger_type']['name'] ?? '' }} &nbsp;|&nbsp; Code: {{ $ledger['code'] ?? '—' }}</p>
    <div class="meta">
        Period: <strong>{{ $from }}</strong> to <strong>{{ $to }}</strong> &nbsp;&bull;&nbsp;
        Generated: @fdatetime(now())
    </div>

    @php
        $fmt = fn($n) => $n !== null ? '₹' . number_format($n, 2) : '—';
        $totalDebit  = collect($rows)->sum('debit');
        $totalCredit = collect($rows)->sum('credit');
    @endphp

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Txn #</th>
                <th>Narration</th>
                <th class="num">Debit (Dr)</th>
                <th class="num">Credit (Cr)</th>
                <th class="num">Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
            <tr>
                <td>{{ $row['date'] }}</td>
                <td style="font-family:monospace;color:#6366f1">{{ $row['transaction_no'] }}</td>
                <td>{{ $row['narration'] ?? '—' }}</td>
                <td class="num" style="color:#4338ca">{{ $fmt($row['debit']) }}</td>
                <td class="num" style="color:#059669">{{ $fmt($row['credit']) }}</td>
                <td class="num" style="font-weight:700">
                    ₹{{ number_format($row['running_balance'], 2) }}
                    <span style="font-size:9px;color:#64748b">{{ $row['running_balance_type'] }}</span>
                </td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="text-align:right;">Totals</td>
                <td class="num" style="color:#4338ca">{{ $fmt($totalDebit) }}</td>
                <td class="num" style="color:#059669">{{ $fmt($totalCredit) }}</td>
                <td class="num">
                    ₹{{ number_format($ledger['balance'] ?? 0, 2) }}
                    <span style="font-size:9px">{{ $ledger['balance_type'] ?? '' }}</span>
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">Generated by School ERP &bull; {{ config('app.name') }}</div>
</body>
</html>
