<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; padding: 28px; }
    h1 { font-size: 18px; font-weight: 800; color: #1e293b; margin-bottom: 2px; }
    .sub { font-size: 11px; color: #64748b; margin-bottom: 16px; }
    .meta { font-size: 10px; color: #64748b; margin-bottom: 18px; border-bottom: 1.5px solid #e2e8f0; padding-bottom: 12px; }
    .net-banner { padding: 12px 18px; border-radius: 6px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: center; }
    .surplus { background: #d1fae5; color: #065f46; }
    .deficit { background: #fee2e2; color: #991b1b; }
    .net-label { font-size: 10px; font-weight: 700; text-transform: uppercase; }
    .net-amount { font-size: 16px; font-weight: 900; font-family: monospace; }
    .section-title { font-size: 12px; font-weight: 800; padding: 8px 12px; margin-top: 14px; margin-bottom: 0; }
    .income-title { background: #f0fdf4; color: #059669; }
    .expense-title { background: #fef2f2; color: #dc2626; }
    table { width: 100%; border-collapse: collapse; }
    thead th { background: #f8fafc; padding: 7px 12px; font-size: 10px; font-weight: 700; text-transform: uppercase; color: #64748b; text-align: left; border-bottom: 1.5px solid #e2e8f0; }
    thead th.num { text-align: right; }
    tbody td { padding: 6px 12px; font-size: 11px; border-bottom: 1px solid #f1f5f9; color: #374151; }
    tbody td.num { text-align: right; font-family: monospace; }
    tfoot td { padding: 8px 12px; font-weight: 700; background: #f8fafc; border-top: 2px solid #e2e8f0; }
    tfoot td.num { text-align: right; font-family: monospace; }
    .footer { margin-top: 20px; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head>
<body>
    <h1>Profit &amp; Loss Statement</h1>
    <p class="sub">Income earned vs expenses incurred in the selected period</p>
    <div class="meta">
        Period: <strong>{{ $from }}</strong> to <strong>{{ $to }}</strong> &nbsp;&bull;&nbsp;
        Generated: {{ now()->format('d M Y, h:i A') }}
    </div>

    @php $fmt = fn($n) => '₹' . number_format(abs($n), 2); @endphp

    <div class="net-banner {{ $netSurplus >= 0 ? 'surplus' : 'deficit' }}">
        <span class="net-label">{{ $netSurplus >= 0 ? 'Net Surplus' : 'Net Deficit' }}</span>
        <span class="net-amount">{{ $fmt($netSurplus) }}</span>
    </div>

    <!-- Income -->
    <div class="section-title income-title">Income — Total: {{ $fmt($totalIncome) }}</div>
    <table>
        <thead><tr><th>Ledger Account</th><th class="num">Amount</th></tr></thead>
        <tbody>
            @foreach($income as $row)
            <tr>
                <td>{{ $row['ledger_name'] }}</td>
                <td class="num" style="color:#059669">{{ $row['amount'] > 0 ? $fmt($row['amount']) : '—' }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr><td style="text-align:right;">Total Income</td><td class="num" style="color:#059669">{{ $fmt($totalIncome) }}</td></tr>
        </tfoot>
    </table>

    <!-- Expenses -->
    <div class="section-title expense-title" style="margin-top:18px;">Expenses — Total: {{ $fmt($totalExpenses) }}</div>
    <table>
        <thead><tr><th>Ledger Account</th><th class="num">Amount</th></tr></thead>
        <tbody>
            @foreach($expenses as $row)
            <tr>
                <td>{{ $row['ledger_name'] }}</td>
                <td class="num" style="color:#dc2626">{{ $row['amount'] > 0 ? $fmt($row['amount']) : '—' }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr><td style="text-align:right;">Total Expenses</td><td class="num" style="color:#dc2626">{{ $fmt($totalExpenses) }}</td></tr>
        </tfoot>
    </table>

    <div class="footer">Generated by School ERP &bull; {{ config('app.name') }}</div>
</body>
</html>
