<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; padding: 28px; }
    h1 { font-size: 18px; font-weight: 800; color: #1e293b; margin-bottom: 2px; }
    .sub { font-size: 11px; color: #64748b; margin-bottom: 16px; }
    .meta { display: flex; gap: 20px; font-size: 10px; color: #64748b; margin-bottom: 18px; border-bottom: 1.5px solid #e2e8f0; padding-bottom: 12px; }
    .bal-banner { padding: 8px 14px; border-radius: 6px; font-size: 11px; font-weight: 600; margin-bottom: 16px; }
    .bal-ok  { background: #d1fae5; color: #065f46; }
    .bal-err { background: #fee2e2; color: #991b1b; }
    table { width: 100%; border-collapse: collapse; }
    thead th { background: #f8fafc; padding: 8px 12px; font-size: 10px; font-weight: 700; text-transform: uppercase; color: #64748b; letter-spacing: 0.04em; text-align: left; border-bottom: 1.5px solid #e2e8f0; }
    thead th.num { text-align: right; }
    tbody td { padding: 7px 12px; font-size: 11px; border-bottom: 1px solid #f1f5f9; color: #374151; }
    tbody td.num { text-align: right; font-family: monospace; }
    tfoot td { padding: 8px 12px; font-weight: 700; background: #f8fafc; border-top: 2px solid #e2e8f0; }
    tfoot td.num { text-align: right; font-family: monospace; }
    .footer { margin-top: 20px; font-size: 9px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head>
<body>
    <h1>Trial Balance</h1>
    <p class="sub">Statement of all ledger account debit and credit balances</p>
    <div class="meta">
        <span>As of: <strong>{{ $asOf }}</strong></span>
        <span>Generated: @fdatetime(now())</span>
    </div>

    @php
        $balanced = round($totalDebit, 2) === round($totalCredit, 2);
        $fmt = fn($n) => number_format(abs($n), 2);
    @endphp

    <div class="bal-banner {{ $balanced ? 'bal-ok' : 'bal-err' }}">
        @if($balanced)
            ✓ Balanced — Total Debit ₹{{ $fmt($totalDebit) }} = Total Credit ₹{{ $fmt($totalCredit) }}
        @else
            ✗ NOT Balanced — Difference: ₹{{ $fmt(abs($totalDebit - $totalCredit)) }}
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Ledger Account</th>
                <th>Type</th>
                <th class="num">Debit (Dr)</th>
                <th class="num">Credit (Cr)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $i => $row)
            <tr>
                <td>{{ $i + 1 }}</td>
                <td>{{ $row['ledger_name'] }}</td>
                <td>{{ $row['ledger_type'] }}</td>
                <td class="num">{{ $row['debit'] > 0 ? '₹' . $fmt($row['debit']) : '—' }}</td>
                <td class="num">{{ $row['credit'] > 0 ? '₹' . $fmt($row['credit']) : '—' }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="text-align:right;">Totals</td>
                <td class="num">₹{{ $fmt($totalDebit) }}</td>
                <td class="num">₹{{ $fmt($totalCredit) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">Generated by School ERP &bull; {{ config('app.name') }}</div>
</body>
</html>
